"""Synthetic, non-explicit training examples. No real children's conversations.
Each row is a separate scenario; evaluation examples live in evaluate.py.
"""
LABELS = ['neutral', 'grooming-trust-building', 'grooming-isolation-request', 'grooming-coercive-language', 'bullying-harassment']
GROUPS = {
'neutral': [
('English', 'How was school today? Want to work on our homework together?'),
('English', 'Great game! See you tomorrow with the rest of the team.'),
('English', 'Please tell your parents where we are meeting for the school project.'),
('English', 'You can always talk to a trusted adult if something makes you uncomfortable.'),
('English', 'I got a new game for my birthday. Do you want to play with our friends?'),
('English', 'Do not send private photos or keep secrets from your family online.'),
('English', 'Our teacher explained why bullying and threats are harmful.'),
('English', 'The surprise birthday party is a secret until Saturday.'),
('Hindi', 'आज स्कूल कैसा था? चलो साथ में होमवर्क करते हैं।'),
('Hindi', 'मम्मी पापा को बताकर दोस्तों के साथ खेलने आना।'),
('Hindi', 'कोई परेशान करे तो किसी भरोसेमंद बड़े से बात करो।'),
('Hindi', 'किसी अनजान को अपनी तस्वीर मत भेजना।'),
('Malayalam', 'ഇന്ന് സ്കൂൾ എങ്ങനെ ഉണ്ടായിരുന്നു? നമുക്ക് ഒരുമിച്ച് പഠിക്കാം.'),
('Malayalam', 'അമ്മയോട് പറഞ്ഞിട്ട് കളിക്കാൻ വരൂ. എല്ലാവരും ഉണ്ടാകും.'),
('Malayalam', 'ആരെങ്കിലും ശല്യം ചെയ്താൽ അധ്യാപകനോട് പറയണം.'),
('Malayalam', 'നാളെ നമുക്ക് കൂട്ടുകാരോടൊപ്പം കളിക്കാം.'),
('Hinglish', 'Kal homework saath mein karte hain, mummy ko bhi bata dena.'),
('Hinglish', 'Koi secret rakhne bole toh parents se baat karna.'),
('Hinglish', 'Aaj match mast tha yaar, kal group mein milte hain.'),
('Manglish', 'Naale namukku friends inte koode kalikkam. Ammayodu paranjittu vaa.'),
('Manglish', 'Homework cheytho? Namukku maths padikkam.'),
('Manglish', 'Aarenkilum budhimuttichaal teacher nodu parayanam.')],
'grooming-trust-building': [
('English', 'You are so mature for your age. Nobody understands you like I do. I can buy you gifts.'),
('English', 'I know we just met but you are my favourite. I will send you game credits if you only talk to me.'),
('English', 'Your friends do not care about you. I am the only person who really gets you. Here is a special gift.'),
('English', 'You are special to me, much more grown up than other kids. I can give you anything you want.'),
('English', 'I will buy you a phone. You can trust me more than anyone in your family.'),
('English', 'Tell me all your personal problems. Only I understand you and I will spoil you with presents.'),
('Hindi', 'तुम अपनी उम्र से बहुत समझदार हो। तुम्हें सिर्फ मैं समझता हूँ। मैं तुम्हें गिफ्ट दूंगा।'),
('Hindi', 'तुम्हारे दोस्त तुम्हारी परवाह नहीं करते। बस मुझ पर भरोसा करो, मैं तुम्हें फोन दिलाऊंगा।'),
('Hindi', 'तुम मेरे लिए खास हो। मैं तुम्हें गेम के पैसे दूंगा, सिर्फ मुझसे बात करो।'),
('Hindi', 'तुम्हें मुझसे अच्छा कोई नहीं समझता। मैं तुम्हारी हर इच्छा पूरी करूंगा।'),
('Malayalam', 'നിന്റെ പ്രായത്തേക്കാൾ പക്വത നിനക്കുണ്ട്. നിന്നെ ഞാൻ മാത്രമേ മനസ്സിലാക്കൂ. സമ്മാനം തരാം.'),
('Malayalam', 'നിന്റെ കൂട്ടുകാർക്ക് നിന്നോട് സ്നേഹമില്ല. എന്നെ മാത്രം വിശ്വസിക്കൂ. ഫോൺ വാങ്ങിത്തരാം.'),
('Malayalam', 'നീ എനിക്ക് വളരെ പ്രത്യേകമാണ്. എന്നോട് മാത്രം സംസാരിച്ചാൽ ഗെയിം ക്രെഡിറ്റ് തരാം.'),
('Hinglish', 'Tum apni age se bahut mature ho. Sirf main tumhe samajhta hoon. Gift bhejun?'),
('Hinglish', 'Main tumhe free diamonds dunga, bas mujhse hi baat karo. Tum mere liye special ho.'),
('Hinglish', 'Tumhare friends care nahi karte. Main hi tumhara true friend hoon, phone gift karunga.'),
('Hinglish', 'Sirf mujhpe trust karo. Tumhe jo chahiye kharid dunga. Tum bahut mature ho.'),
('Manglish', 'Ninte age nekkaal mature aanu nee. Ninne njan maathram manassilaakkum. Gift tharaam.'),
('Manglish', 'Friends ninne care cheyyilla. Enne maathram trust cheyyu, phone vaangi tharaam.'),
('Manglish', 'Nee enikku special aanu. Ennodu maathram chat cheythaal game credits tharaam.')],
'grooming-isolation-request': [
('English', 'Do not tell your parents about us. Delete our chat and move to a private app.'),
('English', 'Keep our friendship secret from your family. Meet me alone without telling anyone.'),
('English', 'Your mum would not understand. Turn off the notifications and message me secretly at night.'),
('English', 'Leave the group and talk to me privately. Nobody else should know we are chatting.'),
('English', 'Are your parents home? Come and meet me alone. Do not bring your friends.'),
('English', 'Promise not to tell a teacher about me. Erase these messages so your family cannot see.'),
('Hindi', 'मम्मी पापा को हमारे बारे में मत बताना। चैट डिलीट कर दो और अकेले मिलने आओ।'),
('Hindi', 'ये बात हमारे बीच रहेगी। घरवालों को नहीं बताना, प्राइवेट चैट पर आओ।'),
('Hindi', 'ग्रुप छोड़कर मुझसे अकेले बात करो। किसी दोस्त को पता नहीं चलना चाहिए।'),
('Hindi', 'क्या तुम्हारे माता पिता घर पर हैं? बिना किसी को बताए अकेले आ जाओ।'),
('Malayalam', 'നമ്മുടെ കാര്യം അമ്മയോടും അച്ഛനോടും പറയരുത്. ചാറ്റ് ഡിലീറ്റ് ചെയ്യൂ. ഒറ്റയ്ക്ക് വരൂ.'),
('Malayalam', 'ഇത് നമ്മുടെ രഹസ്യമാണ്. വീട്ടിൽ പറയരുത്. സ്വകാര്യ ചാറ്റിൽ വരൂ.'),
('Malayalam', 'കൂട്ടുകാരോട് പറയാതെ എന്നെ ഒറ്റയ്ക്ക് കാണാൻ വരണം.'),
('Hinglish', 'Mummy papa ko mat batana. Ye humara secret hai. Private chat pe aao.'),
('Hinglish', 'Chat delete kar dena aur akele milne aana. Kisi ko pata nahi chalna chahiye.'),
('Hinglish', 'Ghar pe koi hai? Bina parents ko bataye milte hain. Friends ko mat lana.'),
('Hinglish', 'Group chhodo aur sirf mujhse DM mein baat karo. Family ko nahi batana.'),
('Manglish', 'Ammayodu parayaruthu. Ithu nammade secret aanu. Private chat il vaa.'),
('Manglish', 'Chat delete cheyyu. Aareyum ariyikkathe ottakku kaanan varanam.'),
('Manglish', 'Veettil parayanda, friends ne kondu vararuthu. Namukku rahasyamaayi kaanam.')],
'grooming-coercive-language': [
('English', 'Send me a personal photo now or I will share your secrets with everyone at school.'),
('English', 'You owe me after all the gifts I bought you. Do what I say or I will expose you.'),
('English', 'If you stop replying I will post your private messages. You have no choice.'),
('English', 'Do not block me. I know where you live and I will hurt you if you tell anyone.'),
('English', 'Meet me tonight or I will leak your pictures to your friends.'),
('English', 'Prove you trust me. Send the photo or I will tell everyone what you said.'),
('Hindi', 'अभी अपनी फोटो भेजो वरना तुम्हारी बातें पूरे स्कूल को बता दूंगा।'),
('Hindi', 'मैंने इतने गिफ्ट दिए हैं, अब मेरी बात मानो नहीं तो बदनाम कर दूंगा।'),
('Hindi', 'मुझे ब्लॉक किया तो तुम्हारे मैसेज सबको भेज दूंगा। तुम्हारे पास कोई रास्ता नहीं है।'),
('Hindi', 'अकेले मिलने आओ नहीं तो तुम्हारी तस्वीरें लीक कर दूंगा।'),
('Malayalam', 'ഇപ്പോൾ ഫോട്ടോ അയയ്ക്കൂ, ഇല്ലെങ്കിൽ നിന്റെ രഹസ്യങ്ങൾ എല്ലാവരോടും പറയും.'),
('Malayalam', 'എന്നെ ബ്ലോക്ക് ചെയ്താൽ നിന്റെ സ്വകാര്യ ചാറ്റ് എല്ലാവർക്കും അയയ്ക്കും.'),
('Malayalam', 'ഞാൻ പറഞ്ഞത് ചെയ്തില്ലെങ്കിൽ നിന്റെ ചിത്രങ്ങൾ പുറത്തുവിടും.'),
('Hinglish', 'Photo bhejo warna tumhari chats sabko dikha dunga. Abhi bhejo.'),
('Hinglish', 'Itne gifts diye hain, ab meri baat maano nahi toh expose kar dunga.'),
('Hinglish', 'Block kiya toh pics leak kar dunga. Tumhare paas choice nahi hai.'),
('Hinglish', 'Aaj milne aao warna school mein sabko secret bata dunga.'),
('Manglish', 'Photo ayakku allenkil ninte secrets ellavarkkum parayum.'),
('Manglish', 'Block cheythaal ninte private chat leak cheyyum. Njan paranjathu cheyyu.'),
('Manglish', 'Gift thannathalle, njan parayunnathu kelkku allenkil photos purathu vidum.')],
'bullying-harassment': [
('English', 'Nobody likes you. You are worthless. Leave our group, loser.'),
('English', 'Everyone laugh at this ugly idiot. We will make fun of you every day.'),
('English', 'You are so stupid. Nobody wants you on the team. Get lost.'),
('English', 'We made a group just to mock you. We will keep posting embarrassing memes about you.'),
('English', 'Shut up loser. We will make sure nobody at school talks to you again.'),
('English', 'You failed again, freak. Everyone should spam this idiot until they leave.'),
('Hindi', 'तुम बेकार हो। कोई तुम्हें पसंद नहीं करता। हमारे ग्रुप से निकल जाओ।'),
('Hindi', 'सब इस बेवकूफ पर हंसो। हम रोज तुम्हारा मजाक उड़ाएंगे।'),
('Hindi', 'तुम बहुत बदसूरत हो। कोई तुमसे बात नहीं करना चाहता।'),
('Hindi', 'हम तुम्हारे बारे में शर्मनाक मीम बनाकर पूरे स्कूल में भेजेंगे।'),
('Malayalam', 'നിന്നെ ആർക്കും ഇഷ്ടമല്ല. നീ ഒരു മണ്ടനാണ്. ഗ്രൂപ്പിൽ നിന്ന് പോ.'),
('Malayalam', 'എല്ലാവരും ഇവനെ കളിയാക്കൂ. എന്നും നിന്നെ പരിഹസിക്കും.'),
('Malayalam', 'നീ ഒന്നിനും കൊള്ളില്ല. ആരും നിന്നോട് സംസാരിക്കില്ല.'),
('Hinglish', 'Tu loser hai, koi tujhe pasand nahi karta. Group se nikal ja.'),
('Hinglish', 'Sab is bewakoof ka mazaak udao. Roz tujhe troll karenge.'),
('Hinglish', 'Teri shakal dekhi hai? Koi tere saath nahi khelega, idiot.'),
('Hinglish', 'Tere embarrassing memes banayenge aur school mein share karenge.'),
('Manglish', 'Nee oru mandan aanu. Aarkkum ninne ishtamalla. Group il ninnu po.'),
('Manglish', 'Ellavarum ivane kaliyaakku. Ennum ninne parihasikkum.'),
('Manglish', 'Nee onninum kollilla. Aarum ninnodu samsarikkilla.')]
}

def training_rows():
    return [{'text': text, 'label': label, 'language': language} for label, rows in GROUPS.items() for language, text in rows]
